version: '3.8'

services:
  dockin-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - dockin-app
    networks:
      - dockin-network

  dockin-app:
    build: .
    env_file:
      - .env
    image: khyojae/dockin-app:latest
    container_name: dockin-app-1
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=DOCKin-DB
      - SPRING_DATASOURCE_URL=jdbc:mysql://DOCKin-DB:3306/dockindb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      DOCKin-DB:
        condition: service_healthy
    networks:
      - dockin-network

  DOCKin-DB:
    image: mysql:8.0.44
    container_name: dockin-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: "dockindb"  # 소문자 dockindb로 수정
    ports:
      - "3306:3306"
    volumes:
      - dockin_db_data:/var/lib/mysql
      # 테이블 충돌 방지를 위해 초기화 SQL은 일단 주석 처리했습니다.
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      timeout: 5s
      retries: 10
      interval: 5s
    networks:
      - dockin-network

networks:
  dockin-network:
    driver: bridge

volumes:
  dockin_db_data: