version: '3.8'

services:
  dockin-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - dockin-app

  dockin-app:
    build: .
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: sync
          path: ./src/main/resources
          target: /app/resources
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://DOCKin-DB:3306/Dockin?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      DOCKin-DB:
        condition: service_healthy

  DOCKin-DB:
    image: mysql:8.0.44
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "Dockin"
    ports:
      - "3306:3306"
    volumes:
      - dockin_db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234" ]
      timeout: 5s
      retries: 10
      interval: 5s

volumes:
  dockin_db_data: